<script type="text/javascript">
	// Option
	var C_TAMPILSEMUACLIENTWMS = GetLanguageByKode('CAPTION-TAMPILSEMUACLIENTWMS');
	var C_TAMPILSEMUAPRINCIPLE = GetLanguageByKode('CAPTION-TAMPILSEMUAPRINCIPLE');
	var C_TAMPILSEMUAPRINCIPLEBRAND = GetLanguageByKode('CAPTION-TAMPILSEMUAPRINCIPLEBRAND');

	var C_TAMBAHJENIS = GetLanguageByKode('CAPTION-TAMBAHJENIS');
	var C_BUATJENISBARU = GetLanguageByKode('CAPTION-BUATJENISBARU');

	var C_PILIHSKUINDUK = GetLanguageByKode('CAPTION-PILIHSKUINDUK');

	var C_PILIHPERUSAHAAN = GetLanguageByKode('CAPTION-PILIHPERUSAHAAN');

	var C_PILIHKATEGORI = GetLanguageByKode('CAPTION-PILIHKATEGORI');
	var C_PILIHSUBKATEGORI = GetLanguageByKode('CAPTION-PILIHSUBKATEGORI');

	var C_PILIHJENIS = GetLanguageByKode('CAPTION-PILIHJENIS');
	var C_PILIHSUBJENIS = GetLanguageByKode('CAPTION-PILIHSUBJENIS');

	var C_PILIHPRINCIPLE = GetLanguageByKode('CAPTION-PILIHPRINCIPLE');
	var C_PILIHBRAND = GetLanguageByKode('CAPTION-PILIHBRAND');

	var C_PILIHUNIT = GetLanguageByKode('CAPTION-PILIHUNIT');
	var C_PILIHAREA = GetLanguageByKode('CAPTION-PILIHAREA');
	var C_CETAKLABEL = GetLanguageByKode('CAPTION-CETAKLABEL');
	var C_TANGGALCETAK = GetLanguageByKode('CAPTION-TANGGALCETAK');
	
	var C_PRINCIPLETIDAKDISET = GetLanguageByKode('CAPTION-PRINCIPLETIDAKDISET');
	var C_TIDAKADADATA = GetLanguageByKode('CAPTION-TIDAKADADATA');

	var C_BARU = GetLanguageByKode('CAPTION-BARU');
	var C_BEKAS = GetLanguageByKode('CAPTION-BEKAS');

	var C_PILIHAPLIKASI = GetLanguageByKode('CAPTION-PILIHAPLIKASI');
	var C_PILIHMENUINDUK = GetLanguageByKode('CAPTION-PILIHMENUINDUK');
	var C_PILIHSUBMENU = GetLanguageByKode('CAPTION-PILIHSUBMENU');
	var C_PILIHSTEP = GetLanguageByKode('CAPTION-PILIHSTEP');
	var C_PILIHICON = GetLanguageByKode('CAPTION-PILIHICON');
	// Placeholder
	var C_PH_SKUINDUK = GetLanguageByKode('CAPTION-PLACEHOLDER-CARISKUINDUK');
	
	var C_PERGIKEMENU = GetLanguageByKode('CAPTION-PERGIKEMENU');
	var C_TIDAKADADETAILINFOLEBIHLANJUT = GetLanguageByKode('CAPTION-TIDAKADADETAILINFOLEBIHLANJUT');
	var C_LIHATINFOLEBIHLANJUT = GetLanguageByKode('CAPTION-LIHATINFOLEBIHLANJUT');
	
	var C_BACK = GetLanguageByKode('CAPTION-BACK');
	var C_BUTUHBANTUAN = GetLanguageByKode('CAPTION-BUTUHBANTUAN');
</script>